### ISSUE TITLE
Indexing Subsidiaries and their email domains

### ISSUE THREAD

**Issue by devashish-gaikwad** [epam/OSCI#79]
Hello,

What is the policy for addition of subsidiaries to the OSCI index ?
Is it a decision of parent company or of EPAM/OSCI on how to list the email domains  ?

Should all subsidiaries of a company be under same umbrella (and index calculation) of parent company
OR
For each subsidiary with a different email domain, a new company addition (and index calculation) with a subsidiary name should be made ?

For example, a company "X" has 2 subsidiaries "Y" and "Z"

Option A:
```
company: X
  domains:
    - X.com
    - Y.com
    - Z.com
```

Option B:
```
company: X
  domains:
    - X.com
    
company: Y
  domains:
    - Y.com
    
company: Z
  domains:
    - Z.com
```

Which would be acceptable ?
